server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: "010622"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: BJ
        #命名空间
#        namespace:
#          22cb4e49-07e4-4208-a287-c36a42ff9e95
#        ephemeral: false # 设置为非临时实例

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
userservice: # 给某个微服务配置负载均衡规则，这里是userservice服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则 # 负载均衡规则
ribbon:
#  开启饥饿加载
  eager-load:
    enabled: true
    clients: userservice
feign:
  #fegin默认底层不会使用连接池，这里开启使用httpclient连接池
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
